name: Run linux based image

on:
  pull_request

jobs:
  wsl:
    name: wsl
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: Vampire/setup-wsl@v3
        with:
          wsl-conf: |
            [wsl2]
            vmIdleTimeout=-1
        #with:
        #  distribution: Ubuntu-24.04
      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.1
      - name: 'Enable networking'
        shell: powershell
        run: |
          wsl.exe --shutdown
          Start-Process wsl.exe -ArgumentList run ./x.sh
          $wslip = ((wsl hostname -I) -split " ")[0]
          echo $wslip
          netsh interface portproxy add v4tov4 listenport=8000 listenaddress=0.0.0.0 connectport=8057 connectaddress=$wslip
          sleep 5
          cargo test
