name: PocketIC test on Windows

on:
  pull_request

jobs:
  pocket_ic_test_windows:
    name: "PocketIC test on Windows"
    runs-on: windows-2022
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Rust and Cargo'
        uses: moonrepo/setup-rust@v1.2.1
      - name: 'Test PocketIC'
        shell: pwsh
        run: |
          wsl.exe --install -d Ubuntu
          Invoke-WebRequest https://download.dfinity.systems/ic/4bd8e1d8430ee17c7e3be47732d1786074ecb592/binaries/x86_64-linux/pocket-ic.gz -OutFile pocket-ic.gz
          Start-Process -NoNewWindow wsl.exe -ArgumentList "gzip -d pocket-ic.gz && chmod +x pocket-ic && ./pocket-ic --ip-addr 0.0.0.0 --port 8057 --ttl 2592000"
          Set-Content -Path host.txt -Value "127.0.0.1" -NoNewLine
          Set-Content -Path port.txt -Value "8057" -NoNewLine
          cargo test
