name: PocketIC test on Windows

on:
  pull_request

jobs:
  pocket_ic_test_windows:
    name: "PocketIC test on Windows"
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
      - uses: Vampire/setup-wsl@v3
      - shell: wsl-bash {0}
        run: |
          sudo apt update && sudo apt install -y ca-certificates
      - name: 'Test PocketIC'
        shell: pwsh
        run: |
          Invoke-WebRequest https://download.dfinity.systems/ic/4bd8e1d8430ee17c7e3be47732d1786074ecb592/binaries/x86_64-linux/pocket-ic.gz -OutFile pocket-ic.gz
          Start-Process -NoNewWindow wsl.exe -ArgumentList "gzip -d pocket-ic.gz && chmod +x pocket-ic && ./pocket-ic --ip-addr 0.0.0.0 --port 8057 --ttl 2592000"
          $wslip = ((wsl hostname -I) -split " ")[0]
          netsh interface portproxy add v4tov4 listenport=8000 listenaddress=0.0.0.0 connectport=8057 connectaddress=$wslip
          cargo test
