name: Run linux based image

on:
  pull_request

jobs:
  wsl:
    name: wsl
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.1
      - uses: Vampire/setup-wsl@v3
        #with:
        #  distribution: Ubuntu-24.04
      - shell: wsl-bash {0}
        run: |
          sudo apt update && sudo apt install -y wget
          wget https://github.com/dfinity/pocketic/releases/download/6.0.0/pocket-ic-x86_64-linux.gz
          gzip -d pocket-ic-x86_64-linux.gz
          mv pocket-ic-x86_64-linux pocket-ic
          chmod +x pocket-ic
          ./pocket-ic --port 8000 &
      - run: |
          cargo test
