name: Run linux based image

on:
  pull_request

jobs:
  wsl:
    name: wsl
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: Vampire/setup-wsl@v3
        #with:
        #  distribution: Ubuntu-24.04
      - name: 'Enable networking'
        shell: powershell
        run: |
          $wslip = ((wsl hostname -I) -split " ")[0]
          echo $wslip
          netsh interface portproxy add v4tov4 listenport=8000 listenaddress=0.0.0.0 connectport=8000 connectaddress=$wslip
      - shell: wsl-bash {0}
        run: |
          sudo apt update && sudo apt install -y wget curl
          wget https://github.com/dfinity/pocketic/releases/download/6.0.0/pocket-ic-x86_64-linux.gz
          wget https://download.dfinity.systems/ic/4bd8e1d8430ee17c7e3be47732d1786074ecb592/binaries/x86_64-linux/pocket-ic.gz
          gzip -d pocket-ic.gz
          chmod +x pocket-ic
          sudo ./pocket-ic --port 8000 --ttl 2592000 &> log.txt &
          sleep 10
          cat log.txt
          curl -X GET -H "Content-Type: application/json" http://localhost:8000/status
          cat log.txt
      - shell: wsl-bash {0}
        run: |
          curl -X GET -H "Content-Type: application/json" http://localhost:8000/status
      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.1
      - run: |
          cargo test
      - shell: wsl-bash {0}
        run: |
          curl -X GET -H "Content-Type: application/json" http://localhost:8000/status
