name: Run linux based image

on:
  pull_request

jobs:
  wsl:
    name: wsl
    runs-on: windows-2022
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: Vampire/setup-wsl@v3
        #with:
        #  distribution: Ubuntu-24.04
      - run: |
          wget https://github.com/dfinity/pocketic/releases/download/6.0.0/pocket-ic-x86_64-linux.gz
          gzip -d pocket-ic-x86_64-linux.gz
          mv pocket-ic-x86_64-linux pocket-ic
          chmod +x pocket-ic
          ./pocket-ic
