name: Run linux based image

on:
  pull_request

jobs:
  wsl:
    name: wsl
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.1
      - name: 'Test PocketIC'
        shell: powershell
        run: |
          wsl.exe --install -d Debian
          Invoke-WebRequest https://download.dfinity.systems/ic/4bd8e1d8430ee17c7e3be47732d1786074ecb592/binaries/x86_64-linux/pocket-ic.gz -OutFile pocket-ic.gz
          Start-Process -NoNewWindow wsl.exe -ArgumentList "gzip -d pocket-ic.gz && chmod +x pocket-ic && ./pocket-ic --ip-addr 0.0.0.0 --port 8057 --ttl 2592000"
          $wslip = ((wsl hostname -I) -split " ")[0]
          $env:POCKET_IC_URL = "http://$wslip:8057"
          echo $env:POCKET_IC_URL
          cargo test
